CREATE TABLE accounts
(
    id             INT          NOT NULL AUTO_INCREMENT,
    `name`         VARCHAR(13)  NOT NULL DEFAULT '',
    password       VARCHAR(128) NOT NULL DEFAULT '',
    pin            VARCHAR(10)  NOT NULL DEFAULT '',
    pic            VARCHAR(26)  NOT NULL DEFAULT '',
    loggedin       TINYINT      NOT NULL DEFAULT '0',
    lastlogin      TIMESTAMP    NULL     DEFAULT NULL,
    createdat      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    birthday       DATE         NOT NULL DEFAULT '2005-05-11',
    banned         TINYINT      NOT NULL DEFAULT '0',
    banreason      TEXT,
    macs           TINYTEXT,
    nxCredit       INT                   DEFAULT NULL,
    maplePoint     INT                   DEFAULT NULL,
    nxPrepaid      INT                   DEFAULT NULL,
    characterslots TINYINT      NOT NULL DEFAULT '3',
    gender         TINYINT      NOT NULL DEFAULT '10',
    tempban        TIMESTAMP    NOT NULL DEFAULT '2005-05-11 00:00:00',
    greason        TINYINT      NOT NULL DEFAULT '0',
    tos            TINYINT      NOT NULL DEFAULT '0',
    sitelogged     TEXT,
    webadmin       INT                   DEFAULT '0',
    nick           VARCHAR(20)           DEFAULT NULL,
    mute           INT                   DEFAULT '0',
    email          VARCHAR(45)           DEFAULT NULL,
    ip             TEXT,
    rewardpoints   INT          NOT NULL DEFAULT '0',
    votepoints     INT          NOT NULL DEFAULT '0',
    hwid           VARCHAR(12)  NOT NULL DEFAULT '',
    language       INT          NOT NULL DEFAULT '2',
    PRIMARY KEY (id),
    UNIQUE KEY `name` (`name`),
    KEY ranking1 (id, banned),
    INDEX (id, `name`),
    INDEX (id, nxCredit, maplePoint, nxPrepaid)
);