# This workflow will build a Java project with Maven

name: Run build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Build with Maven (compile -> test -> package)
      run: mvn -B package --file pom.xml
